version: "3.7"

services:
  api-tests:
    image: api-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
        - ./:/usr/workspace
      command: /bin/sh -c "STAGE=$$STAGE pytest -sv --alluredir=allure-results"
      work_dir: /usr/workspace
      environment:
        STAGE: prod
        SUITE: regression
        API_TOKEN: ${API_TOKEN}

  report:
    image: api-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
        - ./:/usr/workspace
      command: /bin/sh -c "allure generate allure-results --clean -o allure-report"
      work_dir: /usr/workspace
      environment:
        STAGE: prod
        SUITE: regression
        API_TOKEN: ${API_TOKEN}